version: "3.7"

services:

  web:
    image: nginx
    volumes:
      - ./docker/nginx/conf.d:/etc/nginx/conf.d
      - ./src:/var/www/html
    ports:
      - "8080:80"
    depends_on:
      - app
    networks:
      - goal-tracker

  app:
    build:
      context: .
      target: app
    restart: unless-stopped

    environment:
      - DB_CONNECTION=pgsql
      - DB_HOST=database
      - DB_DATABASE=goal_tracker
      - DB_USERNAME=goal_tracker
      - DB_PASSWORD=secret
      - BROADCAST_DRIVER=redis
      - CACHE_DRIVER=redis
      - FILESYSTEM_DRIVER=local
      - QUEUE_CONNECTION=redis
      - SESSION_DRIVER=redis
      - SESSION_LIFETIME=120
      - SESSION_DOMAIN=".goal-tracker.test"
      - REDIS_HOST=cache
      - REDIS_CLIENT=predis
      - APP_NAME="goal-tracker Local"
      - APP_ENV=local
      - APP_DEBUG=true
      - APP_URL=https://goal-tracker.test
    volumes:
      - ./src:/var/www/html
    depends_on:
      - database
      - cache
    networks:
      - goal-tracker

  database:
    container_name: "goal-tracker-database"
    image: postgres
    restart: unless-stopped
    volumes:
      - database:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: goal_tracker
      POSTGRES_USER: goal_tracker
    networks:
      - goal-tracker

  cache:
    container_name: "goal-tracker-cache"
    image: redis:5-alpine
    restart: unless-stopped
    networks:
      - goal-tracker

volumes:
  database:

networks:
  goal-tracker:
    driver: bridge