version: "3.7"

services:

  app:
    build: .
    restart: unless-stopped
    ports:
      - "8000:8000"
    environment:
      - VIRTUAL_HOST=goal-tracker.test # Used for nginx-proxy
      - VIRTUAL_PORT=8000 # Used for nginx-proxy
      - DB_CONNECTION=pgsql
      - DB_HOST=goal-tracker-database-1
      - DB_DATABASE=goal_tracker
      - DB_USERNAME=goal_tracker
      - DB_PASSWORD=secret
      - BROADCAST_DRIVER=redis
      - CACHE_DRIVER=redis
      - FILESYSTEM_DRIVER=local
      - QUEUE_CONNECTION=redis
      - SESSION_DRIVER=redis
      - SESSION_LIFETIME=120
      - SESSION_DOMAIN=".goal-tracker.test"
      - REDIS_HOST=goal-tracker-cache-1
      - REDIS_CLIENT=predis
      - APP_NAME="goal-tracker Local"
      - APP_ENV=local
      - APP_KEY=base64:oq2q+8lo8S3XFUeOhsnPezFclPRrfArB08EJOAzbUtA=
      - APP_DEBUG=true
      - APP_URL=https://goal-tracker.test
    volumes:
      - ./src:/var/www/html
    depends_on:
      - composer
      - database
      - cache
    networks:
      - default
      - external

  # composer
  composer:
    image: composer/composer
    working_dir: /var/www/html
    volumes:
      - ./src:/var/www/html
    command: install

  database:
    image: postgres
    restart: unless-stopped
    volumes:
      - database:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: goal_tracker
      POSTGRES_USER: goal_tracker
    networks:
      - default
      - external

  cache:
    image: redis:5-alpine
    restart: unless-stopped
    networks:
      - default

volumes:
  database:

networks:
  external:
    name: external
  default: